package com.fthlbot.discordbotfthl.core.Annotation;


/**
 * @REGITRATION - COMMANDS RELATED TO REGISTRATION
 * @ROSTER_MANAGEMENT - COMMANDS RELATED TO REPS MANAGING THEIR ROSTER
 * @STAFF - STAFF ONLY COMMANDS
 * @INFO - COMMANDS THAT GIVES INFORMATION ABOUT ANYTHING RELATED TO THE BOT OR THE LEAGUE
 * @SCHEDULING - COMMANDS RELATED TO SCHEDULING THE MATCH
 * @MISC - MISCELLANEOUS COMMANDS THAT CANNOT BE CATEGORISED INTO ANY OTHER CATEGORY
 * @UNSUPPOERTED - COMMANDS THAT ARE NO LONGER SUPPORTED, BUT WILL STILL BE VISIBLE FROM THE HELP COMMAND
 * @TEAM - COMMANDS THAT ARE RELATED TO ONE SPECIFIC TEAM
 * @IGNORE - FULLY FUNCTIONALLY COMMANDS BUT ARE NOT VISIBLE FORM THE HELP FUNCTIONS
 *
 */
public enum CommandType {
    REGISTRATION, ROSTER_MANAGEMENT, STAFF, INFO, SCHEDULE, MISC, UNSUPPORTED, IGNORE, TEAM, CLASH, DEV
}
