# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3        
    - name: Setup jdk-17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Make Gradle Executable
      run: |
        sudo chmod +x gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: sahil2903/discord-bot-fthl
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: upload the jar file to server
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          password:  ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: "docker run -env-file .env -d sahil2903/discord-bot-fthl:latest ."